spring.application.name: config-server
server.port: 8888

spring.cloud.config.server.git:
  uri: https://github.com/BleeeesJc/Enseniamelo_config.git
  default-label: domBranch
  username: DominicEscalante
  password: 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 #Token generado en github
  timeout: 30
  force-pull: true
  clone-on-start: true

spring.security:
  user:
    name: ${CONFIG_SERVER_USR:config-usr}
    password: ${CONFIG_SERVER_PWD:Enseniamelo2025}

# WARNING: Exposing all management endpoints over http should only be used during development, must be locked down in production!
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: info
    org.springframework.cloud.config: DEBUG
#    org.eclipse.jgit: DEBUG

---
spring.config.activate.on-profile: docker
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BleeeesJc/Enseniamelo_config.git
          default-label: domBranch
          username: DominicEscalante
          password: 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
          timeout: 30
          force-pull: true
          clone-on-start: true
