spring:
  application:
    name: mensajes-service

  cloud:
    config:
      failFast: false
      retry:
        max-attempts: 20
        initial-interval: 3000
        multiplier: 1.3
        max-interval: 10000
      uri: http://localhost:8888
      username: ${CONFIG_SERVER_USERNAME:config-usr}
      password: ${CONFIG_SERVER_PWD:}
---
spring:
  config:
    activate:
      on-profile: docker

  cloud:
    config:
      uri: http://config-server:8888
