spring:
  application:
    name: mensajes-service
  config:
    import:
      - optional:configserver:${SPRING_CLOUD_CONFIG_URI}
      - optional:classpath:application-openapi.yml
  cloud:
    config:
      fail-fast: false
      retry:
        max-attempts: 20
        initial-interval: 3000
        multiplier: 1.3
        max-interval: 10000
      uri: http://config-server:8888
      username: ${CONFIG_SERVER_USERNAME:config-usr}
      password: ${CONFIG_SERVER_PWD:Enseniamelo2025}

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    config:
      uri: http://config-server:8888