server:
  port: 8080

spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://config-server:8888"

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: enseniamelo-client
            client-secret: Qf8ZWrnZwht27VCE7u5iyBTwPq0w1Xl9
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        
        provider:
          keycloak:
            authorization-uri: http://localhost:8180/realms/enseniamelo-realm/protocol/openid-connect/auth
            token-uri: http://keycloak:8080/realms/enseniamelo-realm/protocol/openid-connect/token
            user-info-uri: http://keycloak:8080/realms/enseniamelo-realm/protocol/openid-connect/userinfo
            jwk-set-uri: http://keycloak:8080/realms/enseniamelo-realm/protocol/openid-connect/certs
            user-name-attribute: preferred_username
      
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/enseniamelo-realm/protocol/openid-connect/certs
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # ========== RUTAS DE DOCUMENTACIÓN - USUARIOS ==========
        - id: usuarios-openapi-swagger-ui
          uri: lb://usuarios-service
          predicates:
            - Path=/usuarios/openapi/**
          filters:
            - RewritePath=/usuarios/openapi(?<segment>.*), /openapi$\{segment}
            - RemoveRequestHeader=Authorization
          order: -1
        
        - id: usuarios-swagger-ui-alias
          uri: lb://usuarios-service
          predicates:
            - Path=/usuarios/swagger-ui.html,/usuarios/swagger-ui/**
          filters:
            - RewritePath=/usuarios/swagger-ui(?<segment>.*), /openapi/swagger-ui$\{segment}
            - RemoveRequestHeader=Authorization
          order: -1
        
        - id: usuarios-api-docs-alias
          uri: lb://usuarios-service
          predicates:
            - Path=/usuarios/v3/api-docs,/usuarios/v3/api-docs/**
          filters:
            - RewritePath=/usuarios/v3/api-docs(?<segment>.*), /openapi/v3/api-docs$\{segment}
            - RemoveRequestHeader=Authorization
          order: -1
        
        - id: usuarios-webjars
          uri: lb://usuarios-service
          predicates:
            - Path=/usuarios/webjars/**
          filters:
            - RewritePath=/usuarios/webjars(?<segment>.*), /webjars$\{segment}
            - RemoveRequestHeader=Authorization
          order: -1
        
        # ========== RUTAS DE DOCUMENTACIÓN - COMENTARIOS ==========
        - id: comentarios-openapi-swagger-ui
          uri: lb://comentarios-service
          predicates:
            - Path=/comentarios/openapi/**
          filters:
            - RewritePath=/comentarios/openapi(?<segment>.*), /openapi$\{segment}
            - RemoveRequestHeader=Authorization
          order: -1
        
        - id: comentarios-swagger-ui-alias
          uri: lb://comentarios-service
          predicates:
            - Path=/comentarios/swagger-ui.html,/comentarios/swagger-ui/**
          filters:
            - RewritePath=/comentarios/swagger-ui(?<segment>.*), /openapi/swagger-ui$\{segment}
            - RemoveRequestHeader=Authorization
          order: -1
        
        - id: comentarios-api-docs-alias
          uri: lb://comentarios-service
          predicates:
            - Path=/comentarios/v3/api-docs,/comentarios/v3/api-docs/**
          filters:
            - RewritePath=/comentarios/v3/api-docs(?<segment>.*), /openapi/v3/api-docs$\{segment}
            - RemoveRequestHeader=Authorization
          order: -1
        
        - id: comentarios-webjars
          uri: lb://comentarios-service
          predicates:
            - Path=/comentarios/webjars/**
          filters:
            - RewritePath=/comentarios/webjars(?<segment>.*), /webjars$\{segment}
            - RemoveRequestHeader=Authorization
          order: -1
        
        # ========== RUTAS PÚBLICAS  ==========
        - id: auth-public
          uri: lb://usuarios-service
          predicates:
            - Path=/v1/auth/login,/v1/auth/register
          filters:
            - RemoveRequestHeader=Authorization
          order: 0
        
        - id: auth-api-public
          uri: lb://usuarios-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api(?<segment>.*), $\{segment}
            - RemoveRequestHeader=Authorization
          order: 0
        
        # ========== RUTAS DE USUARIOS  ==========
        - id: usuarios-v1-direct
          uri: lb://usuarios-service
          predicates:
            - Path=/v1/usuario,/v1/usuario/**
          order: 1
        
        - id: usuarios-v1-api
          uri: lb://usuarios-service
          predicates:
            - Path=/api/v1/usuario,/api/v1/usuario/**
          filters:
            - RewritePath=/api(?<segment>.*), $\{segment}
          order: 1
        
        - id: tutores-v1-direct
          uri: lb://usuarios-service
          predicates:
            - Path=/v1/tutores,/v1/tutores/**
          order: 1
        
        - id: tutores-v1-api
          uri: lb://usuarios-service
          predicates:
            - Path=/api/v1/tutores,/api/v1/tutores/**
          filters:
            - RewritePath=/api(?<segment>.*), $\{segment}
          order: 1
        
        - id: verificacion-v1-direct
          uri: lb://usuarios-service
          predicates:
            - Path=/v1/verificacion,/v1/verificacion/**
          order: 1
        
        # ========== RUTAS COMENTARIOS - PÚBLICAS ==========
        - id: comentarios-api-public-get
          uri: lb://comentarios-service
          predicates:
            - Path=/api/comentario-curso,/api/comentario-curso/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Authorization
          order: 0

        - id: comentarios-api-secured-mutate
          uri: lb://comentarios-service
          predicates:
            - Path=/api/comentario-curso,/api/comentario-curso/**
            - Method=POST,PUT,DELETE
          order: 0
        
        # ========== EUREKA ==========
        - id: eureka-web-start
          uri: http://eureka-server:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
          order: 2
        
        - id: eureka-web-other
          uri: http://eureka-server:8761
          predicates:
            - Path=/eureka/**
          order: 2

      # ========== CORS ==========
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:3000"
              - "http://localhost:4200"
              - "http://localhost:5173"
              - "http://localhost:8080"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders:
              - Authorization
            allowCredentials: true
            maxAge: 3600

# ========== EUREKA ==========
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    preferIpAddress: true
    hostname: gateway-service
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    non-secure-port-enabled: true
    non-secure-port: 8080
    secure-port-enabled: false

# ========== ACTUATOR ==========
management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"

# ========== LOGGING ==========
logging:
  level:
    root: INFO
    '[org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator]': INFO
    '[org.springframework.cloud.gateway]': DEBUG
    '[org.springframework.security]': DEBUG
    '[org.springframework.security.oauth2]': DEBUG