services:
  postgres:
<<<<<<< HEAD
    image: postgres:15-alpine
    container_name: keycloak-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - enseniamelo-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: keycloak
    depends_on:
      - postgres
    ports:
      - "8080:8080"
=======
    image: postgres:15
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-net
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.1
    command: start-dev
    ports:
      - 8080:8080
>>>>>>> origin/domBranch
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
<<<<<<< HEAD
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
    command: start-dev
    networks:
      - enseniamelo-network

=======
    depends_on:
      - postgres
    networks:
      - microservices-net
>>>>>>> origin/domBranch
volumes:
  postgres_data:

networks:
<<<<<<< HEAD
  enseniamelo-network:
    external: true  
=======
  microservices-net:
>>>>>>> origin/domBranch
