version: "3.9"

services:
  cursoservice:
    build: .
    container_name: cursoservice
    env_file:
      - ./.env
    environment:
      LOG_LEVEL: "DEBUG"   # ejemplo
    ports:
      - "8000:8000"
    restart: unless-stopped
