spring.config.import: "optional:configserver:http://configserver:8888"
spring:
  application.name: gateway-service
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    uri: http://config-server:8888
    username: ${CONFIG_SERVER_USR:config-usr}
    password: ${CONFIG_SERVER_PWD:Enseniamelo2025}
---
spring.config.activate.on-profile: docker

spring.cloud.config.uri: http://config-server:8888
