# payments-service.yml  (repositorio Enseniamelo_config)

# üîπ Configuraci√≥n propia del ms de pagos
APP_NAME: payments-service
APP_PORT: 8002

# Estos valores se usar√°n solo si quieres sobreescribir lo global
EUREKA_APP_NAME: PAYMENTS-SERVICE

---
spring.config.activate.on-profile: docker

# Overrides espec√≠ficos para Docker
APP_PORT: 8002
EUREKA_APP_NAME: PAYMENTS-SERVICE
EUREKA_INSTANCE_HOST: payments-service
EUREKA_INSTANCE_PORT: 8002
