springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: com.enseniamelo.tutorservice.controller
  pathsToMatch: /**

api:
  common:
    version: 1.0.0
    title: API tutor
    description: Servicio de información de tutores de "enseñamelo"
    termsOfService: https://www.enseñamelo.com/tutores
    license: Licencia MIT
    licenseUrl: https://opensource.org/licenses/MIT
    externalDocDesc: Documentación en Wiki
    externalDocUrl: https://www.enseñamelo.com/wiki
    contact:
      name: Soporte Enseñamelo
      url: https://www.enseñamelo.com/contacto
      email: soporte@enseñamelo.com

  responseCodes:
    ok.description: OK
    badRequest.description: Bad Request, Formato inválido de la solicitud. Ver mensaje de respuesta para más información.
    notFound.description: Not found, el id especificado no existe.
    unprocessableEntity.description: Unprocessable entity, no se puede procesar los parametros de entrada. Ver mensaje de respuesta para más información.

  tutor:
    get-tutor:
      description: Retorna la información del tutor en base al id de tutor proporcionado.
      notes: |
        # Respuesta exitosa
        Si el id del tutor solicitado es encontrado el método retornará la información del tutor

        # Respuestas con error
        1. Si ningún tutor se encontró se devuelve un error **404 - Not Found**
      parameters:
        tutorId: ID del tutor a buscar
    get-tutors:
      description: Retorna la lista de todos los tutores.
      notes: |
        # Respuesta exitosa
        Si se encuentran tutores, el método retornará la lista de tutores.

        # Respuestas con error
        1. Si no se encontraron tutores se devuelve un error **404 - Not Found**